name: mauve
version: 0.1.0.0
github: "raptazure/mauve"
license: BSD3
author: "raptazure"
maintainer: "hermit0x9@outlook.com"
copyright: "2021 raptazure"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/raptazure/mauve#readme>

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - process

library:
  source-dirs: src
  exposed-modules:
    - BadApple
    - Compose
    - Play

executables:
  mauve-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - mauve

tests:
  mauve-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - mauve
